name: Deploy LMS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Backend update
        run: |
          cd backend
          git pull origin main
          npm install --legacy-peer-deps
          npm run build
          npm run migration:run
          sudo systemctl restart lms-backend

      - name: Frontend update
        run: |
          cd ../frontend
          git pull origin main
          npm install --legacy-peer-deps
          npm run build
          sudo systemctl reload nginx
