name: Frontend Deploy

on:
    push:
        branches: [main, develop]
        paths:
            - 'frontend/**'
    pull_request:
        branches: [main]
        paths:
            - 'frontend/**'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'
                  cache-dependency-path: frontend/package-lock.json

            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci

            - name: Build frontend
              working-directory: ./frontend
              run: npm run build:prod
              env:
                  VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
                  VITE_TELEGRAM_BOT_USERNAME: ${{ secrets.VITE_TELEGRAM_BOT_USERNAME }}

            - name: Verify build output
              run: |
                  echo "Checking if index.html exists..."
                  ls -la frontend/dist/
                  if [ ! -f "frontend/dist/index.html" ]; then
                    echo "❌ index.html not found in dist folder!"
                    exit 1
                  fi
                  echo "✅ index.html found successfully!"

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-dist
                  path: frontend/dist/
                  retention-days: 30

        # Uncomment and configure for your deployment method
        # - name: Deploy to server
        #   uses: appleboy/ssh-action@v1.0.3
        #   with:
        #     host: ${{ secrets.SERVER_HOST }}
        #     username: ${{ secrets.SERVER_USERNAME }}
        #     key: ${{ secrets.SERVER_SSH_KEY }}
        #     script: |
        #       cd /var/www/html
        #       rm -rf dist_backup
        #       mv dist dist_backup || true
        #       mkdir -p dist
        #
        # - name: Copy files to server
        #   uses: appleboy/scp-action@v0.1.7
        #   with:
        #     host: ${{ secrets.SERVER_HOST }}
        #     username: ${{ secrets.SERVER_USERNAME }}
        #     key: ${{ secrets.SERVER_SSH_KEY }}
        #     source: "frontend/dist/*"
        #     target: "/var/www/html/dist/"
        #     strip_components: 2
